### ISSUE TITLE
SQL error when saving a product with lots of options

### ISSUE THREAD

**Issue by SteveEdson** [Merchello/Merchello#2014] opened 2017-09-12 15:40 UTC
i'm trying to save a product that has about 5 options, each has about 3 to 16 choices, this is generating a lot of variants, and has just started failing to save, with the error:

```
The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
```

When saving product variants, I think it needs to chunk up the collection into smaller groups, rather than trying to do it all at once.

https://github.com/Merchello/Merchello/blob/710570432c8ab77b0bf39a69952705b670f46d72/src/Merchello.Core/Services/ProductVariantService.cs#L262-L271

<details>
<summary>Full stack trace here</summary>
<pre>
<code>
ERROR Umbraco.Core.Persistence.UmbracoDatabase - Exception (4dae37cc).
System.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs:line 235
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.<>c__DisplayClass4.<ExecuteReaderWithRetry>b__3()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteReaderWithRetry(IDbCommand command, RetryPolicy cmdRetryPolicy, RetryPolicy conRetryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteReaderWithRetry(IDbCommand command, RetryPolicy retryPolicy)
   at Umbraco.Core.Persistence.PetaPocoCommandExtensions.ExecuteReaderWithRetry(IDbCommand command)
   at Umbraco.Core.Persistence.Database.<Query>d__7`1.MoveNext()
</code>
</pre>
</details>

**Comment by SteveEdson** [comment] 2017-09-12 15:48
Would something like the following would be suitable instead?

```objective-c
foreach (var variantChunk in productVariants.Split(500))
{
	var uow = UowProvider.GetUnitOfWork();
	using (var repository = RepositoryFactory.CreateProductVariantRepository(uow))
	{
		foreach (var variant in variantChunk)
		{
			repository.AddOrUpdate(variant);
		}
		//uow.Commit();
		uow.CommitBulk<IProductVariant>();
	}
}
```

**Comment by SteveEdson** [comment] 2017-09-12 19:55
It looks like this might already have been addressed here: https://github.com/Merchello/Merchello/blob/master/src/Merchello.Core/Persistence/Repositories/MerchelloBulkOperationRepository.cs#L165

However I'm not sure that this is being used in this case.

**Comment by cwjackso** [comment] 2017-09-12 20:44
Something like this should make it use the  bulk operations part as ProductVariantRepository already extends BulkOperationRepository
`            using (new WriteLock(Locker))
            {
                var uow = UowProvider.GetUnitOfWork();
                using (var repository = RepositoryFactory.CreateProductVariantRepository(uow))
                {

                    var variantsGroup = productVariants.GroupBy(x => x.HasIdentity);

                    var enumerable = variantsGroup as IGrouping<bool, IProductVariant>[] ?? variantsGroup.ToArray();

                    if (enumerable.FirstOrDefault(x => x.Key) != null)
                    {
                        repository.PersistUpdatedItems(enumerable.FirstOrDefault(x => x.Key));
                    }
                    if (enumerable.FirstOrDefault(x => !x.Key) != null)
                    {
                        repository.PersistNewItems(enumerable.FirstOrDefault(x => !x.Key));
                    }
                    //uow.Commit();
                    uow.CommitBulk<IProductVariant>();
                }
            }`

**Comment by YodasMyDad** [comment] 2017-09-13 05:36
This has already been addressed. The fix will be in the next release. Both the save and create performance and the load of the page after

https://github.com/Merchello/Merchello/commit/e6fe1e032c42e468f9a484fdf51dbf20cd3d4d8b

And 

https://github.com/Merchello/Merchello/commit/c297c8a21b963717e0d8cf7111b7b8a91d79579c

**Closed by YodasMyDad** 2017-09-13 05:36 UTC

**Comment by cwjackso** [comment] 2017-09-13 06:52
Hi Lee,

Any chance of a patch release on the 2.5.x branch so we can keep using nuget in our deployments and don't have to put bleeding edge code on production? 

We have a major build for one of our clients going live in 1 week and have just discovered this breaking issue on the site whilst populating some complex products.

Your help would be much approciated

Thanks

Carl

**Comment by YodasMyDad** [comment] 2017-09-13 08:10
The problem is, the nuget package is just the binaries and there have been angular and view changes too since then. I'll speak to @rustyswayne  and see if we can do a release.

**Comment by cwjackso** [comment] 2017-09-15 10:31
Hi, Lee

Any movement on this?

**Comment by YodasMyDad** [comment] 2017-09-15 10:32
Yes. Will be a release later today or Monday next week. Just trying to align timezones.

**Comment by SteveEdson** [comment] 2017-09-21 13:10
Any update on this? Thanks!

**Comment by YodasMyDad** [comment] 2017-09-21 15:05
We have just found there is a breaking change in Umbraco between last version and new one. Trying to find the time to update it.

**Comment by DMCK96** [comment] 2018-11-26 13:30
Just curious before I update has this been resolved? 

I'm curious as to whether there is a way to not automatically generate every potential variant. Due to it using exponential growth it quickly gets out of control (7 options with 5 values tries to generate over 78,000 variants). For something that may only have 30 or so available variants, I can't expect users to scroll through 78,000 variants to find those correct 30, there will be a lot of human error.

On top of that this is only for 1 product, if this is done on say 90 products we're talking over 7 million variants. 

Surely there has to be a way of turning off this automatic generation of variants.

**Comment by cwjackso** [comment] 2018-11-26 13:36
Hi,

It's still an issue in the main merchello but it's worth looking at our PR here https://github.com/Merchello/Merchello/pull/2182

It allows for a product to be marked with "use virtual variants" and then exposes a method on the helper to generate product variants on the fly.

Thanks.

Carl

**Comment by DMCK96** [comment] 2018-11-26 14:16
> Hi,
> 
> It's still an issue in the main merchello but it's worth looking at our PR here #2182
> 
> It allows for a product to be marked with "use virtual variants" and then exposes a method on the helper to generate product variants on the fly.
> 
> Thanks.
> 
> Carl

Would that PR still allow for use of extended product data? As that content cannot be generated automatically. Sadly it's the automatic generation of variants which is the problem itself here.

**Comment by christophermacdee** [comment] 2018-11-27 11:18
I have a similar situation where I have a product which has 7 product options and each has 7-15 choices . By the the time I have added the 5th option, it take forever to  save and it loads indefinitely. Would the virtual variants solve this issue?

**Comment by DMCK96** [comment] 2018-11-27 11:31
> I have a similar situation where I have a product which has 7 product options and each has 7-15 choices . By the the time I have added the 5th option, it take forever to save and it loads indefinitely. Would the virtual variants solve this issue?

Check your umbraco application log, it'll be getting the same SQL error due to too many parameters. The virtual variants do act as a way around this but you lose access to editing extended content of each variant as far as I know and I don't think it'd be great performance wise; nonetheless it is a workaround for the SQL error and would resolve your issue.

In my case though the virtual variants isn't something I can use and I'd be worried about performance when it's generating 75,000 variants for each product (whether this happens on application startup or when a product view is loaded I've not looked into enough to know).

**Comment by cwjackso** [comment] 2018-11-27 12:50
In our solution the variant is generated in the fly everyone it is needed it's never added to the database. Performance wise it's not noticeably slower than normal as individual variant generation is very fast.

Yes you lose the ability to extend a variant, but we have extend shared attributes to give variants price markups and additional data. This works well for us.

Thanks
