### ISSUE TITLE
Delete Associated Product Content Types not possible

### ISSUE THREAD

**Issue by Vrijdagonline** [Merchello/Merchello#2116] opened 2017-12-25 15:14 UTC
It seems that an associated Product Content Type can't be deleted once added...

![image](https://user-images.githubusercontent.com/5910058/34341001-8ac8e1be-e98e-11e7-858e-d56531ccc174.png)

Or I am missing something ;)
Umbraco: 7.7.7
Merchello: 2.6.0

Cheers,
Arjan

**Comment by donaldgray** [comment] 2018-01-29 20:42
I'm seeing the same behaviour - is this by design or an issue? 

I found it confusing as I delete a content type that was used and now I'm left with a stub that doesn't do anything and I can't get rid of.

**Comment by medarke** [comment] 2018-06-29 19:55
I'm seeing this too..... I am using Merchello 2.6.0 in Umbraco Cloud. Umbraco 7.10.4

On my Local, I can see the issue, but in the cloud it works. I see the delete icon.

Strange.

**Comment by YodasMyDad** [comment] 2018-10-17 15:28
I think this is by design to stop people wiping out large amounts of data or their entire store by accidentally deleting one. The delete button shows when the sites is in debug mode

`$scope.debugAllowDelete = Umbraco.Sys.ServerVariables.isDebuggingEnabled;`

I'm going to close this as although it's annoying. I think it has potential to cause a lot of damage so will just leave as is.

**Closed by YodasMyDad** 2018-10-17 15:28 UTC
Labels: Bug
